### ISSUE TITLE
build with nix on macosx

### ISSUE THREAD

**Issue by smunix** [luc-tielen/eclair-lang#14]
add x86_68-darwin to allow building with macos

**Comment by kpadmasola** [comment]
@luc-tielen I am interested in working on this issue. Can you please provide pointers for me to get started? I know basic Haskell but have not used Nix before. Is there a Discord channel or any other channel where we can discuss? Thanks!

**Comment by luc-tielen** [comment]
@kpadmasola there is no Discord for Eclair yet, though maybe I should make one. For now, if you want, you can DM me on Twitter [@luctielen](https://twitter.com/luctielen).

For this PR I doubt you will be touching any Haskell code (I might be wrong on this).
You will mainly need to do changes to the `*.nix` files in the root directory of this repo. (Probably only `flake.nix`?)

Hopefully, with a bit of luck, it's as simple as adding `"x86_64-darwin"` and `"aarch64-darwin"` to the list found [here](https://github.com/luc-tielen/eclair-lang/blob/main/flake.nix#L26).

You can check if it works by then running `nix build` on your OSX machine.

**Comment by kpadmasola** [comment]
@luc-tielen Thanks, Can you point me to any starter docs on how to setup nix? I have never used nix so asking.

**Comment by luc-tielen** [comment]
@smunix might know this better than me, but I think nix.dev (https://nix.dev/tutorials/install-nix#macos) and https://nixos.org/learn.html are good places to start.

For the syntax: https://learnxinyminutes.com/docs/nix/.

That being said.. I really hope it's as simple as adding those 2 strings I mentioned. But probably not. :sweat_smile:

**Comment by kpadmasola** [comment]
thanks @luc-tielen . I'll start with those pointers and will keep you updated on how it goes.

**Comment by smunix** [comment]
@kpadmasola hit me up at https://discord.gg/r5AYhzvh if you need help or have further questions
